=== opnfv/parser/verigraph/tester/testcase_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Testcase",
    "description": "A testcase for VeriGraph",
    "type": "object",
    "properties": {
        "id": {
            "description": "The unique identifier for a testcase",
            "type": "integer"
        },
        "name": {
            "description": "Name of the testcase",
            "type": "string"
        },
        "description": {
            "description": "A description for the testcase, specifying what is going to be tested",
            "type": "string"
        },
        "policy_url_parameters": {
            "description": "The set of parameters to be passed in GET request to the verification service",
            "type": "string"
        },
        "result": {
            "description": "The set of parameters to be passed in GET request to the verification service",
            "type": "string"
        },
        "graph": {
        	"description": "The graph to be tested",
        	"type": "object"
        }
    },
    "required": ["id", "name", "policy_url_parameters", "result", "graph"]
}

=== opnfv/parser/verigraph/tester/testcases/test_user_nat_vpn_webserver_sat.json
{
	"id": 3,
	"name": "nat_vpn_test_case",
	"description": "This test case contains a graph with client, nat, vpn and server",
	"policy_url_parameters": "?type=reachability&source=user1&destination=webserver",
	"result": "SAT",
	"graph": {
	   "nodes":[
	      {
	         "name":"user1",
	         "functional_type":"endhost",
	         "neighbours":[
	            {
	               "name":"nat"
	            }
	         ],
	        "configuration": 
	            [
					{
						"body": "cartoon",
						"protocol": "HTTP_REQUEST",
						"destination": "webserver"
					}
	            ]
	      },
	      {
	         "name":"nat",
	         "functional_type":"nat",
	         "neighbours":[
	            {
	               "name":"user1"
	            },
	            {
	               "name":"vpnaccess"
	            }
	         ],
	         "configuration":[
	            "user1"
	         ]
	      },
	      {
	         "name":"vpnaccess",
	         "functional_type":"vpnaccess",
	         "neighbours":[
	         	{
	               "name":"nat"
	            },
	            {
	               "name":"vpnexit"
	            }
	         ],
	         "configuration":[
	            {"vpnexit": "vpnexit"}
	         ]
	      },
	      {
	         "name":"vpnexit",
	         "functional_type":"vpnexit",
	         "neighbours":[
	            {
	               "name":"vpnaccess"
	            },
	            {
	               "name":"webserver"
	            }
	         ],
	         "configuration":[
	            {"vpnaccess": "vpnaccess"}
	         ]
	      },
	      {
	         "name":"webserver",
	         "functional_type":"webserver",
	         "neighbours":[
	         	{
	         		"name": "vpnexit"
	         	}
	         ]
	      }
	   ]
	}
}

=== opnfv/parser/verigraph/tester/testcases/test_webserver_vpn_nat_user_unsat.json
{
	"id": 5,
	"name": "nat_vpn_test_case_serv_to_user",
	"description": "This test case contains a graph with client, nat, vpn and server. webserver -> client",
	"policy_url_parameters": "?type=reachability&source=webserver&destination=user1",
	"result": "UNSAT",
	"graph": {
	   "nodes":[
	      {
	         "name":"user1",
	         "functional_type":"endhost",
	         "neighbours":[
	            {
	               "name":"nat"
	            }
	         ],
	        "configuration": 
	            [
					{
						"body": "cartoon",
						"protocol": "HTTP_REQUEST",
						"destination": "webserver"
					}
	            ]
	      },
	      {
	         "name":"nat",
	         "functional_type":"nat",
	         "neighbours":[
	            {
	               "name":"user1"
	            },
	            {
	               "name":"vpnaccess"
	            }
	         ],
	         "configuration":[
	            "user1"
	         ]
	      },
	      {
	         "name":"vpnaccess",
	         "functional_type":"vpnaccess",
	         "neighbours":[
	         	{
	               "name":"nat"
	            },
	            {
	               "name":"vpnexit"
	            }
	         ],
	         "configuration":[
	            {"vpnexit": "vpnexit"}
	         ]
	      },
	      {
	         "name":"vpnexit",
	         "functional_type":"vpnexit",
	         "neighbours":[
	            {
	               "name":"vpnaccess"
	            },
	            {
	               "name":"webserver"
	            }
	         ],
	         "configuration":[
	            {"vpnaccess": "vpnaccess"}
	         ]
	      },
	      {
	         "name":"webserver",
	         "functional_type":"webserver",
	         "neighbours":[
	         	{
	         		"name": "vpnexit"
	         	}
	         ]
	      }
	   ]
	}
}

=== opnfv/parser/verigraph/tester/testcases/test_user_nat_vpn_fieldmod_webserver_unsat.json
{
	"id": 4,
	"name": "nat_vpn_with_fieldmodifier_test_case",
	"description": "This test case contains a graph with client, nat, vpn (with field mod in between) and server",
	"policy_url_parameters": "?type=reachability&source=user1&destination=webserver",
	"result": "UNSAT",
	"graph": {
	   "nodes":[
	      {
	         "name":"user1",
	         "functional_type":"endhost",
	         "neighbours":[
	            {
	               "name":"nat"
	            }
	         ],
	        "configuration": 
	            [
					{
						"body": "cartoon",
						"protocol": "HTTP_REQUEST",
						"destination": "webserver"
					}
	            ]
	      },
	      {
	         "name":"nat",
	         "functional_type":"nat",
	         "neighbours":[
	            {
	               "name":"user1"
	            },
	            {
	               "name":"vpnaccess"
	            }
	         ],
	         "configuration":[
	            "user1"
	         ]
	      },
	      {
	         "name":"vpnaccess",
	         "functional_type":"vpnaccess",
	         "neighbours":[
	         	{
	               "name":"nat"
	            },
	            {
	               "name":"fieldmodifier"
	            }
	         ],
	         "configuration":[
	            {"vpnexit": "vpnexit"}
	         ]
	      },
	      {
	         "name":"fieldmodifier",
	         "functional_type":"fieldmodifier",
	         "neighbours":[
	         	{
	               "name":"vpnaccess"
	            },
	            {
	               "name":"vpnexit"
	            }
	         ]
	      },
	      {
	         "name":"vpnexit",
	         "functional_type":"vpnexit",
	         "neighbours":[
	            {
	               "name":"fieldmodifier"
	            },
	            {
	               "name":"webserver"
	            }
	         ],
	         "configuration":[
	            {"vpnaccess": "vpnaccess"}
	         ]
	      },
	      {
	         "name":"webserver",
	         "functional_type":"webserver",
	         "neighbours":[
	         	{
	         		"name": "vpnexit"
	         	}
	         ]
	      }
	   ]
	}
}
